sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tCehPswKCs6cEWQVfvR
    access-key-secret: Yc4Y9tq5EsLSdptzXlaeND5DHMtn0b
    bucket-name: sky-take-out-jackson-firsttime
  redis:
    host: localhost
    port: 6379
    password: 12345678
    database: 1
  wechat:
    appid: wx492b1b461c1d1b98
    secret: c3d052c6b31bdb9271d55ffde5883440
